wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.20
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.12
    t:
      1:
      - 3
      2:
      - 3
      4: 3.6.12
      5: 0.10.20
      8:
      - 5
arenaCompare:
  desc: null
  value: 10
checkpoint:
  desc: null
  value: ./temp/episodentests/80/
cpuct:
  desc: null
  value: 1
load_folder_file:
  desc: null
  value:
  - /dev/models/8x100x50
  - best
load_model:
  desc: null
  value: false
maxlenOfQueue:
  desc: null
  value: 200
numEps:
  desc: null
  value: 10
numIters:
  desc: null
  value: 1000
numItersForTrainExamplesHistory:
  desc: null
  value: 20
numMCTSSims:
  desc: null
  value: 25
tempThreshold:
  desc: null
  value: 15
updateThreshold:
  desc: null
  value: 0.6
